// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package com.nebula.mooc.chatserver.core;

public final class ChatMessage {
    private ChatMessage() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface requestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:request)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string content = 1;</code>
         */
        java.lang.String getContent();

        /**
         * <code>string content = 1;</code>
         */
        com.google.protobuf.ByteString
        getContentBytes();

        /**
         * <code>int32 color = 2;</code>
         */
        int getColor();
    }

    /**
     * Protobuf type {@code request}
     */
    public static final class request extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:request)
            requestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use request.newBuilder() to construct.
        private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private request() {
            content_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private request(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            content_ = s;
                            break;
                        }
                        case 16: {

                            color_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_request_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.nebula.mooc.chatserver.core.ChatMessage.request.class, com.nebula.mooc.chatserver.core.ChatMessage.request.Builder.class);
        }

        public static final int CONTENT_FIELD_NUMBER = 1;
        private volatile java.lang.Object content_;

        /**
         * <code>string content = 1;</code>
         */
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            }
        }

        /**
         * <code>string content = 1;</code>
         */
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int COLOR_FIELD_NUMBER = 2;
        private int color_;

        /**
         * <code>int32 color = 2;</code>
         */
        public int getColor() {
            return color_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getContentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
            }
            if (color_ != 0) {
                output.writeInt32(2, color_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getContentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
            }
            if (color_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, color_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.nebula.mooc.chatserver.core.ChatMessage.request)) {
                return super.equals(obj);
            }
            com.nebula.mooc.chatserver.core.ChatMessage.request other = (com.nebula.mooc.chatserver.core.ChatMessage.request) obj;

            if (!getContent()
                    .equals(other.getContent())) return false;
            if (getColor()
                    != other.getColor()) return false;
            return unknownFields.equals(other.unknownFields);
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (37 * hash) + COLOR_FIELD_NUMBER;
            hash = (53 * hash) + getColor();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.nebula.mooc.chatserver.core.ChatMessage.request prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:request)
                com.nebula.mooc.chatserver.core.ChatMessage.requestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_request_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_request_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.nebula.mooc.chatserver.core.ChatMessage.request.class, com.nebula.mooc.chatserver.core.ChatMessage.request.Builder.class);
            }

            // Construct using com.nebula.mooc.chatserver.core.ChatMessage.request.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                content_ = "";

                color_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_request_descriptor;
            }

            @java.lang.Override
            public com.nebula.mooc.chatserver.core.ChatMessage.request getDefaultInstanceForType() {
                return com.nebula.mooc.chatserver.core.ChatMessage.request.getDefaultInstance();
            }

            @java.lang.Override
            public com.nebula.mooc.chatserver.core.ChatMessage.request build() {
                com.nebula.mooc.chatserver.core.ChatMessage.request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.nebula.mooc.chatserver.core.ChatMessage.request buildPartial() {
                com.nebula.mooc.chatserver.core.ChatMessage.request result = new com.nebula.mooc.chatserver.core.ChatMessage.request(this);
                result.content_ = content_;
                result.color_ = color_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.nebula.mooc.chatserver.core.ChatMessage.request) {
                    return mergeFrom((com.nebula.mooc.chatserver.core.ChatMessage.request) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.nebula.mooc.chatserver.core.ChatMessage.request other) {
                if (other == com.nebula.mooc.chatserver.core.ChatMessage.request.getDefaultInstance()) return this;
                if (!other.getContent().isEmpty()) {
                    content_ = other.content_;
                    onChanged();
                }
                if (other.getColor() != 0) {
                    setColor(other.getColor());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.nebula.mooc.chatserver.core.ChatMessage.request parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.nebula.mooc.chatserver.core.ChatMessage.request) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object content_ = "";

            /**
             * <code>string content = 1;</code>
             */
            public java.lang.String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string content = 1;</code>
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                java.lang.Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string content = 1;</code>
             */
            public Builder setContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                content_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string content = 1;</code>
             */
            public Builder clearContent() {

                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }

            /**
             * <code>string content = 1;</code>
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                content_ = value;
                onChanged();
                return this;
            }

            private int color_;

            /**
             * <code>int32 color = 2;</code>
             */
            public int getColor() {
                return color_;
            }

            /**
             * <code>int32 color = 2;</code>
             */
            public Builder setColor(int value) {

                color_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 color = 2;</code>
             */
            public Builder clearColor() {

                color_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:request)
        }

        // @@protoc_insertion_point(class_scope:request)
        private static final com.nebula.mooc.chatserver.core.ChatMessage.request DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.nebula.mooc.chatserver.core.ChatMessage.request();
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.request getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<request>
                PARSER = new com.google.protobuf.AbstractParser<request>() {
            @java.lang.Override
            public request parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new request(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<request> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<request> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.nebula.mooc.chatserver.core.ChatMessage.request getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface responseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:response)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string content = 1;</code>
         */
        java.lang.String getContent();

        /**
         * <code>string content = 1;</code>
         */
        com.google.protobuf.ByteString
        getContentBytes();

        /**
         * <code>int32 color = 2;</code>
         */
        int getColor();

        /**
         * <code>string nickname = 3;</code>
         */
        java.lang.String getNickname();

        /**
         * <code>string nickname = 3;</code>
         */
        com.google.protobuf.ByteString
        getNicknameBytes();

        /**
         * <code>int64 timestamp = 4;</code>
         */
        long getTimestamp();
    }

    /**
     * Protobuf type {@code response}
     */
    public static final class response extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:response)
            responseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use response.newBuilder() to construct.
        private response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private response() {
            content_ = "";
            nickname_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private response(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            content_ = s;
                            break;
                        }
                        case 16: {

                            color_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            nickname_ = s;
                            break;
                        }
                        case 32: {

                            timestamp_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_response_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_response_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.nebula.mooc.chatserver.core.ChatMessage.response.class, com.nebula.mooc.chatserver.core.ChatMessage.response.Builder.class);
        }

        public static final int CONTENT_FIELD_NUMBER = 1;
        private volatile java.lang.Object content_;

        /**
         * <code>string content = 1;</code>
         */
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            }
        }

        /**
         * <code>string content = 1;</code>
         */
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int COLOR_FIELD_NUMBER = 2;
        private int color_;

        /**
         * <code>int32 color = 2;</code>
         */
        public int getColor() {
            return color_;
        }

        public static final int NICKNAME_FIELD_NUMBER = 3;
        private volatile java.lang.Object nickname_;

        /**
         * <code>string nickname = 3;</code>
         */
        public java.lang.String getNickname() {
            java.lang.Object ref = nickname_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                nickname_ = s;
                return s;
            }
        }

        /**
         * <code>string nickname = 3;</code>
         */
        public com.google.protobuf.ByteString
        getNicknameBytes() {
            java.lang.Object ref = nickname_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                nickname_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 4;
        private long timestamp_;

        /**
         * <code>int64 timestamp = 4;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getContentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
            }
            if (color_ != 0) {
                output.writeInt32(2, color_);
            }
            if (!getNicknameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickname_);
            }
            if (timestamp_ != 0L) {
                output.writeInt64(4, timestamp_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getContentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
            }
            if (color_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, color_);
            }
            if (!getNicknameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickname_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(4, timestamp_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.nebula.mooc.chatserver.core.ChatMessage.response)) {
                return super.equals(obj);
            }
            com.nebula.mooc.chatserver.core.ChatMessage.response other = (com.nebula.mooc.chatserver.core.ChatMessage.response) obj;

            if (!getContent()
                    .equals(other.getContent())) return false;
            if (getColor()
                    != other.getColor()) return false;
            if (!getNickname()
                    .equals(other.getNickname())) return false;
            if (getTimestamp()
                    != other.getTimestamp()) return false;
            return unknownFields.equals(other.unknownFields);
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (37 * hash) + COLOR_FIELD_NUMBER;
            hash = (53 * hash) + getColor();
            hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
            hash = (53 * hash) + getNickname().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.nebula.mooc.chatserver.core.ChatMessage.response prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code response}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:response)
                com.nebula.mooc.chatserver.core.ChatMessage.responseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_response_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_response_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.nebula.mooc.chatserver.core.ChatMessage.response.class, com.nebula.mooc.chatserver.core.ChatMessage.response.Builder.class);
            }

            // Construct using com.nebula.mooc.chatserver.core.ChatMessage.response.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                content_ = "";

                color_ = 0;

                nickname_ = "";

                timestamp_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.nebula.mooc.chatserver.core.ChatMessage.internal_static_response_descriptor;
            }

            @java.lang.Override
            public com.nebula.mooc.chatserver.core.ChatMessage.response getDefaultInstanceForType() {
                return com.nebula.mooc.chatserver.core.ChatMessage.response.getDefaultInstance();
            }

            @java.lang.Override
            public com.nebula.mooc.chatserver.core.ChatMessage.response build() {
                com.nebula.mooc.chatserver.core.ChatMessage.response result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.nebula.mooc.chatserver.core.ChatMessage.response buildPartial() {
                com.nebula.mooc.chatserver.core.ChatMessage.response result = new com.nebula.mooc.chatserver.core.ChatMessage.response(this);
                result.content_ = content_;
                result.color_ = color_;
                result.nickname_ = nickname_;
                result.timestamp_ = timestamp_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.nebula.mooc.chatserver.core.ChatMessage.response) {
                    return mergeFrom((com.nebula.mooc.chatserver.core.ChatMessage.response) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.nebula.mooc.chatserver.core.ChatMessage.response other) {
                if (other == com.nebula.mooc.chatserver.core.ChatMessage.response.getDefaultInstance()) return this;
                if (!other.getContent().isEmpty()) {
                    content_ = other.content_;
                    onChanged();
                }
                if (other.getColor() != 0) {
                    setColor(other.getColor());
                }
                if (!other.getNickname().isEmpty()) {
                    nickname_ = other.nickname_;
                    onChanged();
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.nebula.mooc.chatserver.core.ChatMessage.response parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.nebula.mooc.chatserver.core.ChatMessage.response) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object content_ = "";

            /**
             * <code>string content = 1;</code>
             */
            public java.lang.String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string content = 1;</code>
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                java.lang.Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string content = 1;</code>
             */
            public Builder setContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                content_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string content = 1;</code>
             */
            public Builder clearContent() {

                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }

            /**
             * <code>string content = 1;</code>
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                content_ = value;
                onChanged();
                return this;
            }

            private int color_;

            /**
             * <code>int32 color = 2;</code>
             */
            public int getColor() {
                return color_;
            }

            /**
             * <code>int32 color = 2;</code>
             */
            public Builder setColor(int value) {

                color_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 color = 2;</code>
             */
            public Builder clearColor() {

                color_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object nickname_ = "";

            /**
             * <code>string nickname = 3;</code>
             */
            public java.lang.String getNickname() {
                java.lang.Object ref = nickname_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    nickname_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string nickname = 3;</code>
             */
            public com.google.protobuf.ByteString
            getNicknameBytes() {
                java.lang.Object ref = nickname_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    nickname_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string nickname = 3;</code>
             */
            public Builder setNickname(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                nickname_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string nickname = 3;</code>
             */
            public Builder clearNickname() {

                nickname_ = getDefaultInstance().getNickname();
                onChanged();
                return this;
            }

            /**
             * <code>string nickname = 3;</code>
             */
            public Builder setNicknameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                nickname_ = value;
                onChanged();
                return this;
            }

            private long timestamp_;

            /**
             * <code>int64 timestamp = 4;</code>
             */
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>int64 timestamp = 4;</code>
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 timestamp = 4;</code>
             */
            public Builder clearTimestamp() {

                timestamp_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:response)
        }

        // @@protoc_insertion_point(class_scope:response)
        private static final com.nebula.mooc.chatserver.core.ChatMessage.response DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.nebula.mooc.chatserver.core.ChatMessage.response();
        }

        public static com.nebula.mooc.chatserver.core.ChatMessage.response getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<response>
                PARSER = new com.google.protobuf.AbstractParser<response>() {
            @java.lang.Override
            public response parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new response(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<response> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<response> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.nebula.mooc.chatserver.core.ChatMessage.response getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_request_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_request_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_response_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_response_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021ChatMessage.proto\")\n\007request\022\017\n\007conten" +
                        "t\030\001 \001(\t\022\r\n\005color\030\002 \001(\005\"O\n\010response\022\017\n\007co" +
                        "ntent\030\001 \001(\t\022\r\n\005color\030\002 \001(\005\022\020\n\010nickname\030\003" +
                        " \001(\t\022\021\n\ttimestamp\030\004 \001(\003B0\n\037com.nebula.mo" +
                        "oc.chatserver.coreB\013ChatMessageH\001b\006proto" +
                        "3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_request_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_request_descriptor,
                new java.lang.String[]{"Content", "Color",});
        internal_static_response_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_response_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_response_descriptor,
                new java.lang.String[]{"Content", "Color", "Nickname", "Timestamp",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
